apiVersion: v1
kind: Service
metadata:
  name: spire-server-federation
  namespace: zero-trust-workload-identity-manager
  labels:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  ports:
  - name: federation
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/instance: cluster-zero-trust-workload-identity-manager

