apiVersion: v1
data:
  server.conf: |-
    {
      "health_checks": {
        "bind_address": "0.0.0.0",
        "bind_port": "8080",
        "listener_enabled": true,
        "live_path": "/live",
        "ready_path": "/ready"
      },
      "plugins": {
        "DataStore": [
          {
            "sql": {
              "plugin_data": {
                "connection_string": "/run/spire/data/datastore.sqlite3",
                "database_type": "sqlite3",
                "disable_migration": false,
                "max_idle_conns": 2,
                "max_open_conns": 100
              }
            }
          }
        ],
        "KeyManager": [
          {
            "disk": {
              "plugin_data": {
                "keys_path": "/run/spire/data/keys.json"
              }
            }
          }
        ],
        "NodeAttestor": [
          {
            "k8s_psat": {
              "plugin_data": {
                "clusters": [
                  {
                    "cluster-2": {
                      "allowed_node_label_keys": [],
                      "allowed_pod_label_keys": [],
                      "audience": [
                        "spire-server"
                      ],
                      "service_account_allow_list": [
                        "zero-trust-workload-identity-manager:spire-agent"
                      ]
                    }
                  }
                ]
              }
            }
          }
        ],
        "Notifier": [
          {
            "k8sbundle": {
              "plugin_data": {
                "config_map": "spire-bundle",
                "namespace": "zero-trust-workload-identity-manager"
              }
            }
          }
        ]
      },
      "server": {
        "audit_log_enabled": false,
        "bind_address": "0.0.0.0",
        "bind_port": "8081",
        "ca_key_type": "rsa-2048",
        "ca_subject": [
          {
            "common_name": "apps.cluster-2.devcluster.openshift.com",
            "country": [
              "US"
            ],
            "organization": [
              "RH"
            ]
          }
        ],
        "ca_ttl": "24h0m0s",
        "data_dir": "/run/spire/data",
        "default_jwt_svid_ttl": "5m0s",
        "default_x509_svid_ttl": "1h0m0s",
        "jwt_issuer": "https://oidc-discovery.apps.cluster-2.devcluster.openshift.com",
        "log_level": "debug",
        "trust_domain": "apps.cluster-2.devcluster.openshift.com",
        "federation": {
          "bundle_endpoint": {
            "address": "0.0.0.0",
            "port": 8443
          },
          "federates_with": {
            "apps.cluster-1.devcluster.openshift.com": {
              "bundle_endpoint_url": "https://spire-server-federation-zero-trust-workload-identity-manager.apps.cluster-1.devcluster.openshift.com",
              "bundle_endpoint_profile": {
                "https_spiffe": {
                  "endpoint_spiffe_id": "spiffe://apps.cluster-1.devcluster.openshift.com/spire/server"
                }
              }
            }
          }
        }
      },
      "telemetry": {
        "Prometheus": {
          "host": "0.0.0.0",
          "port": "9402"
        }
      }
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/instance: cluster-zero-trust-workload-identity-manager
    app.kubernetes.io/managed-by: zero-trust-workload-identity-manager
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: zero-trust-workload-identity-manager
    app.kubernetes.io/version: 1.12.4
  name: spire-server
  namespace: zero-trust-workload-identity-manager
