---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: non-federated-frontend
  namespace: federation-demo
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: non-federated-frontend
spec:
  spiffeIDTemplate: "spiffe://apps.cluster-1.devcluster.openshift.com/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}"
  podSelector:
    matchLabels:
      app: non-federated-frontend
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: federation-demo
  # NO federatesWith - federation disabled!
  className: zero-trust-workload-identity-manager-spire
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: non-federated-frontend-api
  namespace: federation-demo
data:
  app.py: |
    from flask import Flask, jsonify
    import requests
    import subprocess
    import time
    import threading
    from datetime import datetime

    app = Flask(__name__)

    backend_url = "http://non-federated-backend.federation-demo.svc.cluster.local:8081/api/data"

    def get_spiffe_info():
        try:
            result = subprocess.run(
                ['/spire-agent', 'api', 'fetch', 'x509', 
                 '-socketPath', '/spiffe-workload-api/spire-agent.sock',
                 '-write', '/tmp/'],
                capture_output=True, text=True, timeout=10
            )
            
            svid_result = subprocess.run(
                ['openssl', 'x509', '-in', '/tmp/svid.0.pem', '-noout', '-text'],
                capture_output=True, text=True
            )
            
            spiffe_id = "unknown"
            for line in svid_result.stdout.split('\n'):
                if 'URI:spiffe://' in line:
                    spiffe_id = line.strip().split('URI:')[1]
                    break
            
            bundle_count = subprocess.run(
                ['grep', '-c', 'BEGIN CERTIFICATE', '/tmp/bundle.0.pem'],
                capture_output=True, text=True
            )
            
            return {
                'spiffe_id': spiffe_id,
                'bundle_count': int(bundle_count.stdout.strip()) if bundle_count.returncode == 0 else 0
            }
        except Exception as e:
            return {'error': str(e)}

    def call_backend_loop():
        time.sleep(15)  # Wait for backend
        while True:
            try:
                print("")
                print("=" * 70)
                print(f"[{datetime.now().strftime('%H:%M:%S')}] 📤 CALLING NON-FEDERATED BACKEND API...")
                print(f"Target: {backend_url}")
                print(f"⚠️  Expected result: This WILL work (both in same cluster)")
                print("-" * 70)
                
                # Note: This is HTTP not HTTPS, and both are in cluster-2, 
                # so it might work, but demonstrates the configuration difference
                response = requests.get(backend_url, timeout=10)
                
                print(f"[{datetime.now().strftime('%H:%M:%S')}] Response status: {response.status_code}")
                
                if response.status_code == 200:
                    data = response.json()
                    print(f"✅ Got response (but backend shouldn't serve cluster-1 clients)")
                else:
                    data = response.json()
                    print(f"❌ Backend rejected request (EXPECTED):")
                    print(f"   {data.get('error')}")
                    print(f"   Reason: Backend has NO cluster-1 trust bundle")
                
            except Exception as e:
                print(f"[{datetime.now().strftime('%H:%M:%S')}] ❌ Connection FAILED (EXPECTED): {e}")
                print(f"   This is CORRECT - no federation configured!")
            
            print("")
            print("⏳ Waiting 30 seconds before next call...")
            print("=" * 70)
            time.sleep(30)

    @app.route('/', methods=['GET'])
    def index():
        spiffe_info = get_spiffe_info()
        return jsonify({
            'service': 'non-federated-frontend',
            'cluster': 'cluster-1',
            'spiffe_id': spiffe_info.get('spiffe_id'),
            'bundles': spiffe_info.get('bundle_count'),
            'backend_url': backend_url,
            'federation_enabled': False,
            'warning': 'Cannot communicate with cluster-2 backends'
        }), 200

    if __name__ == '__main__':
        print("=" * 70)
        print("🚀 NON-FEDERATED FRONTEND CLIENT (Cluster 1)")
        print("⚠️  WARNING: Federation is DISABLED")
        print("=" * 70)
        print("")
        
        spiffe_info = get_spiffe_info()
        print(f"✅ My SPIFFE ID: {spiffe_info.get('spiffe_id')}")
        print(f"✅ Trust bundles: {spiffe_info.get('bundle_count')} certificate(s)")
        print(f"❌ Federation: DISABLED - No cluster-2 bundle")
        print("")
        print(f"🎯 Will try calling backend at: {backend_url}")
        print(f"⚠️  Expected: Calls will fail (no federation)")
        print("")
        
        thread = threading.Thread(target=call_backend_loop, daemon=True)
        thread.start()
        
        print("🌐 Starting frontend web server on 0.0.0.0:8081...")
        app.run(host='0.0.0.0', port=8081, debug=False)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: non-federated-frontend
  namespace: federation-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: non-federated-frontend
  template:
    metadata:
      labels:
        app: non-federated-frontend
    spec:
      serviceAccountName: non-federated-frontend
      containers:
      - name: api
        image: python:3.11-slim
        command: ["/bin/bash", "-c"]
        args:
        - |
          pip install flask requests --quiet
          apt-get update -qq && apt-get install -y openssl curl wget -qq
          wget -q https://github.com/spiffe/spire/releases/download/v1.10.0/spire-1.10.0-linux-amd64-musl.tar.gz
          tar xzf spire-1.10.0-linux-amd64-musl.tar.gz
          cp spire-1.10.0/bin/spire-agent /spire-agent
          chmod +x /spire-agent
          
          while [ ! -S /spiffe-workload-api/spire-agent.sock ]; do
            echo "Waiting for SPIFFE socket..."
            sleep 2
          done
          
          python /app/app.py
        ports:
        - containerPort: 8081
          name: http
        volumeMounts:
        - name: spiffe-workload-api
          mountPath: /spiffe-workload-api
          readOnly: true
        - name: app
          mountPath: /app
      volumes:
      - name: spiffe-workload-api
        csi:
          driver: csi.spiffe.io
          readOnly: true
      - name: app
        configMap:
          name: non-federated-frontend-api
---
apiVersion: v1
kind: Service
metadata:
  name: non-federated-frontend
  namespace: federation-demo
spec:
  selector:
    app: non-federated-frontend
  ports:
  - port: 8081
    targetPort: 8081
    name: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: non-federated-frontend
  namespace: federation-demo
spec:
  to:
    kind: Service
    name: non-federated-frontend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

