apiVersion: v1
data:
  server.conf: |
    {
      "health_checks": {
        "bind_address": "0.0.0.0",
        "bind_port": "8080",
        "listener_enabled": true,
        "live_path": "/live",
        "ready_path": "/ready"
      },
      "plugins": {
        "DataStore": [
          {
            "sql": {
              "plugin_data": {
                "connection_string": "/run/spire/data/datastore.sqlite3",
                "database_type": "sqlite3",
                "disable_migration": false,
                "max_idle_conns": 2,
                "max_open_conns": 100
              }
            }
          }
        ],
        "KeyManager": [
          {
            "disk": {
              "plugin_data": {
                "keys_path": "/run/spire/data/keys.json"
              }
            }
          }
        ],
        "NodeAttestor": [
          {
            "k8s_psat": {
              "plugin_data": {
                "clusters": [
                  {
                    "rausingh-1": {
                      "allowed_node_label_keys": [],
                      "allowed_pod_label_keys": [],
                      "audience": [
                        "spire-server"
                      ],
                      "service_account_allow_list": [
                        "zero-trust-workload-identity-manager:spire-agent"
                      ]
                    }
                  }
                ]
              }
            }
          }
        ],
        "Notifier": [
          {
            "k8sbundle": {
              "plugin_data": {
                "config_map": "spire-bundle",
                "namespace": "zero-trust-workload-identity-manager"
              }
            }
          }
        ]
      },
      "server": {
        "audit_log_enabled": false,
        "bind_address": "0.0.0.0",
        "bind_port": "8081",
        "ca_key_type": "rsa-2048",
        "ca_subject": [
          {
            "common_name": "apps.mykastur14.gcp.devcluster.openshift.com",
            "country": [
              "US"
            ],
            "organization": [
              "RH"
            ]
          }
        ],
        "ca_ttl": "24h0m0s",
        "data_dir": "/run/spire/data",
        "default_jwt_svid_ttl": "5m0s",
        "default_x509_svid_ttl": "1h0m0s",
        "jwt_issuer": "https://oidc-discovery.apps.mykastur14.gcp.devcluster.openshift.com",
        "log_level": "debug",
        "trust_domain": "apps.mykastur14.gcp.devcluster.openshift.com",
        "federation": {
          "bundle_endpoint": {
            "address": "0.0.0.0",
            "port": 8443
          },
          "federates_with": {
            "apps.aagnihot-cluster-kdh.devcluster.openshift.com": {
              "bundle_endpoint_url": "https://spire-server-federation-zero-trust-workload-identity-manager.apps.aagnihot-cluster-kdh.devcluster.openshift.com",
              "bundle_endpoint_profile": {
                "https_spiffe": {
                  "endpoint_spiffe_id": "spiffe://apps.aagnihot-cluster-kdh.devcluster.openshift.com/spire/server"
                }
              }
            }
          }
        }
      },
      "telemetry": {
        "Prometheus": {
          "host": "0.0.0.0",
          "port": "9402"
        }
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"server.conf":"{\n  \"health_checks\": {\n    \"bind_address\": \"0.0.0.0\",\n    \"bind_port\": \"8080\",\n    \"listener_enabled\": true,\n    \"live_path\": \"/live\",\n    \"ready_path\": \"/ready\"\n  },\n  \"plugins\": {\n    \"DataStore\": [\n      {\n        \"sql\": {\n          \"plugin_data\": {\n            \"connection_string\": \"/run/spire/data/datastore.sqlite3\",\n            \"database_type\": \"sqlite3\",\n            \"disable_migration\": false,\n            \"max_idle_conns\": 2,\n            \"max_open_conns\": 100\n          }\n        }\n      }\n    ],\n    \"KeyManager\": [\n      {\n        \"disk\": {\n          \"plugin_data\": {\n            \"keys_path\": \"/run/spire/data/keys.json\"\n          }\n        }\n      }\n    ],\n    \"NodeAttestor\": [\n      {\n        \"k8s_psat\": {\n          \"plugin_data\": {\n            \"clusters\": [\n              {\n                \"rausingh-1\": {\n                  \"allowed_node_label_keys\": [],\n                  \"allowed_pod_label_keys\": [],\n                  \"audience\": [\n                    \"spire-server\"\n                  ],\n                  \"service_account_allow_list\": [\n                    \"zero-trust-workload-identity-manager:spire-agent\"\n                  ]\n                }\n              }\n            ]\n          }\n        }\n      }\n    ],\n    \"Notifier\": [\n      {\n        \"k8sbundle\": {\n          \"plugin_data\": {\n            \"config_map\": \"spire-bundle\",\n            \"namespace\": \"zero-trust-workload-identity-manager\"\n          }\n        }\n      }\n    ]\n  },\n  \"server\": {\n    \"audit_log_enabled\": false,\n    \"bind_address\": \"0.0.0.0\",\n    \"bind_port\": \"8081\",\n    \"ca_key_type\": \"rsa-2048\",\n    \"ca_subject\": [\n      {\n        \"common_name\": \"apps.mykastur14.gcp.devcluster.openshift.com\",\n        \"country\": [\n          \"US\"\n        ],\n        \"organization\": [\n          \"RH\"\n        ]\n      }\n    ],\n    \"ca_ttl\": \"24h0m0s\",\n    \"data_dir\": \"/run/spire/data\",\n    \"default_jwt_svid_ttl\": \"5m0s\",\n    \"default_x509_svid_ttl\": \"1h0m0s\",\n    \"jwt_issuer\": \"https://oidc-discovery.apps.mykastur14.gcp.devcluster.openshift.com\",\n    \"log_level\": \"debug\",\n    \"trust_domain\": \"apps.mykastur14.gcp.devcluster.openshift.com\",\n    \"federation\": {\n      \"bundle_endpoint\": {\n        \"address\": \"0.0.0.0\",\n        \"port\": 8443\n      },\n      \"federates_with\": {\n        \"apps.aagnihot-cluster-kdh.devcluster.openshift.com\": {\n          \"bundle_endpoint_url\": \"https://spire-server-federation-zero-trust-workload-identity-manager.apps.aagnihot-cluster-kdh.devcluster.openshift.com\",\n          \"bundle_endpoint_profile\": {\n            \"https_spiffe\": {\n              \"endpoint_spiffe_id\": \"spiffe://apps.aagnihot-cluster-kdh.devcluster.openshift.com/spire/server\"\n            }\n          }\n        }\n      }\n    }\n  },\n  \"telemetry\": {\n    \"Prometheus\": {\n      \"host\": \"0.0.0.0\",\n      \"port\": \"9402\"\n    }\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"control-plane","app.kubernetes.io/instance":"cluster-zero-trust-workload-identity-manager","app.kubernetes.io/managed-by":"zero-trust-workload-identity-manager","app.kubernetes.io/name":"spire-server"},"name":"spire-server","namespace":"zero-trust-workload-identity-manager"}}
  creationTimestamp: "2025-10-17T12:40:59Z"
  labels:
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/instance: cluster-zero-trust-workload-identity-manager
    app.kubernetes.io/managed-by: zero-trust-workload-identity-manager
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: zero-trust-workload-identity-manager
    app.kubernetes.io/version: 1.12.4
  name: spire-server
  namespace: zero-trust-workload-identity-manager
  ownerReferences:
  - apiVersion: operator.openshift.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: SpireServer
    name: cluster
    uid: 3c97269b-9d2f-4d85-85ca-c5939733ab7a
  resourceVersion: "587412"
  uid: 276362ee-a151-4021-8e2e-5b255ae32c37
